// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GeoNode.proto
// Protobuf Java Version: 4.28.0-dev
package net.cz88.czdb.protobuf;

public final class GeoNodeOuterClass {
  private GeoNodeOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "-dev",
      GeoNodeOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GeoNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GeoNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required sint32 code = 1;</code>
     * @return Whether the code field is set.
     */
    boolean hasCode();
    /**
     * <code>required sint32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string provinceCode = 3;</code>
     * @return Whether the provinceCode field is set.
     */
    boolean hasProvinceCode();
    /**
     * <code>optional string provinceCode = 3;</code>
     * @return The provinceCode.
     */
    java.lang.String getProvinceCode();
    /**
     * <code>optional string provinceCode = 3;</code>
     * @return The bytes for provinceCode.
     */
    com.google.protobuf.ByteString
        getProvinceCodeBytes();

    /**
     * <code>optional string cityCode = 4;</code>
     * @return Whether the cityCode field is set.
     */
    boolean hasCityCode();
    /**
     * <code>optional string cityCode = 4;</code>
     * @return The cityCode.
     */
    java.lang.String getCityCode();
    /**
     * <code>optional string cityCode = 4;</code>
     * @return The bytes for cityCode.
     */
    com.google.protobuf.ByteString
        getCityCodeBytes();

    /**
     * <code>optional string districtCode = 5;</code>
     * @return Whether the districtCode field is set.
     */
    boolean hasDistrictCode();
    /**
     * <code>optional string districtCode = 5;</code>
     * @return The districtCode.
     */
    java.lang.String getDistrictCode();
    /**
     * <code>optional string districtCode = 5;</code>
     * @return The bytes for districtCode.
     */
    com.google.protobuf.ByteString
        getDistrictCodeBytes();

    /**
     * <code>optional string lat = 6;</code>
     * @return Whether the lat field is set.
     */
    boolean hasLat();
    /**
     * <code>optional string lat = 6;</code>
     * @return The lat.
     */
    java.lang.String getLat();
    /**
     * <code>optional string lat = 6;</code>
     * @return The bytes for lat.
     */
    com.google.protobuf.ByteString
        getLatBytes();

    /**
     * <code>optional string lng = 7;</code>
     * @return Whether the lng field is set.
     */
    boolean hasLng();
    /**
     * <code>optional string lng = 7;</code>
     * @return The lng.
     */
    java.lang.String getLng();
    /**
     * <code>optional string lng = 7;</code>
     * @return The bytes for lng.
     */
    com.google.protobuf.ByteString
        getLngBytes();

    /**
     * <code>optional string zone = 8;</code>
     * @return Whether the zone field is set.
     */
    boolean hasZone();
    /**
     * <code>optional string zone = 8;</code>
     * @return The zone.
     */
    java.lang.String getZone();
    /**
     * <code>optional string zone = 8;</code>
     * @return The bytes for zone.
     */
    com.google.protobuf.ByteString
        getZoneBytes();

    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    java.util.List<GeoNodeOuterClass.GeoNode> 
        getSubNodeList();
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    GeoNodeOuterClass.GeoNode getSubNode(int index);
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    int getSubNodeCount();
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    java.util.List<? extends GeoNodeOuterClass.GeoNodeOrBuilder> 
        getSubNodeOrBuilderList();
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    GeoNodeOuterClass.GeoNodeOrBuilder getSubNodeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GeoNode}
   */
  public static final class GeoNode extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GeoNode)
      GeoNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "-dev",
        GeoNode.class.getName());
    }
    // Use GeoNode.newBuilder() to construct.
    private GeoNode(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GeoNode() {
      name_ = "";
      provinceCode_ = "";
      cityCode_ = "";
      districtCode_ = "";
      lat_ = "";
      lng_ = "";
      zone_ = "";
      subNode_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeoNodeOuterClass.internal_static_GeoNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeoNodeOuterClass.internal_static_GeoNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GeoNodeOuterClass.GeoNode.class, GeoNodeOuterClass.GeoNode.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <code>required sint32 code = 1;</code>
     * @return Whether the code field is set.
     */
    @java.lang.Override
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required sint32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVINCECODE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object provinceCode_ = "";
    /**
     * <code>optional string provinceCode = 3;</code>
     * @return Whether the provinceCode field is set.
     */
    @java.lang.Override
    public boolean hasProvinceCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string provinceCode = 3;</code>
     * @return The provinceCode.
     */
    @java.lang.Override
    public java.lang.String getProvinceCode() {
      java.lang.Object ref = provinceCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          provinceCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string provinceCode = 3;</code>
     * @return The bytes for provinceCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProvinceCodeBytes() {
      java.lang.Object ref = provinceCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provinceCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITYCODE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cityCode_ = "";
    /**
     * <code>optional string cityCode = 4;</code>
     * @return Whether the cityCode field is set.
     */
    @java.lang.Override
    public boolean hasCityCode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string cityCode = 4;</code>
     * @return The cityCode.
     */
    @java.lang.Override
    public java.lang.String getCityCode() {
      java.lang.Object ref = cityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cityCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cityCode = 4;</code>
     * @return The bytes for cityCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityCodeBytes() {
      java.lang.Object ref = cityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISTRICTCODE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object districtCode_ = "";
    /**
     * <code>optional string districtCode = 5;</code>
     * @return Whether the districtCode field is set.
     */
    @java.lang.Override
    public boolean hasDistrictCode() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string districtCode = 5;</code>
     * @return The districtCode.
     */
    @java.lang.Override
    public java.lang.String getDistrictCode() {
      java.lang.Object ref = districtCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          districtCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string districtCode = 5;</code>
     * @return The bytes for districtCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDistrictCodeBytes() {
      java.lang.Object ref = districtCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        districtCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lat_ = "";
    /**
     * <code>optional string lat = 6;</code>
     * @return Whether the lat field is set.
     */
    @java.lang.Override
    public boolean hasLat() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string lat = 6;</code>
     * @return The lat.
     */
    @java.lang.Override
    public java.lang.String getLat() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lat_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lat = 6;</code>
     * @return The bytes for lat.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLatBytes() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LNG_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lng_ = "";
    /**
     * <code>optional string lng = 7;</code>
     * @return Whether the lng field is set.
     */
    @java.lang.Override
    public boolean hasLng() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string lng = 7;</code>
     * @return The lng.
     */
    @java.lang.Override
    public java.lang.String getLng() {
      java.lang.Object ref = lng_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lng_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lng = 7;</code>
     * @return The bytes for lng.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLngBytes() {
      java.lang.Object ref = lng_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lng_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZONE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object zone_ = "";
    /**
     * <code>optional string zone = 8;</code>
     * @return Whether the zone field is set.
     */
    @java.lang.Override
    public boolean hasZone() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string zone = 8;</code>
     * @return The zone.
     */
    @java.lang.Override
    public java.lang.String getZone() {
      java.lang.Object ref = zone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string zone = 8;</code>
     * @return The bytes for zone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getZoneBytes() {
      java.lang.Object ref = zone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBNODE_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private java.util.List<GeoNodeOuterClass.GeoNode> subNode_;
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    @java.lang.Override
    public java.util.List<GeoNodeOuterClass.GeoNode> getSubNodeList() {
      return subNode_;
    }
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    @java.lang.Override
    public java.util.List<? extends GeoNodeOuterClass.GeoNodeOrBuilder> 
        getSubNodeOrBuilderList() {
      return subNode_;
    }
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    @java.lang.Override
    public int getSubNodeCount() {
      return subNode_.size();
    }
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    @java.lang.Override
    public GeoNodeOuterClass.GeoNode getSubNode(int index) {
      return subNode_.get(index);
    }
    /**
     * <code>repeated .GeoNode subNode = 9;</code>
     */
    @java.lang.Override
    public GeoNodeOuterClass.GeoNodeOrBuilder getSubNodeOrBuilder(
        int index) {
      return subNode_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSubNodeCount(); i++) {
        if (!getSubNode(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeSInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, provinceCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, cityCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, districtCode_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, lat_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, lng_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, zone_);
      }
      for (int i = 0; i < subNode_.size(); i++) {
        output.writeMessage(9, subNode_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, provinceCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, cityCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, districtCode_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, lat_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, lng_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, zone_);
      }
      for (int i = 0; i < subNode_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, subNode_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GeoNodeOuterClass.GeoNode)) {
        return super.equals(obj);
      }
      GeoNodeOuterClass.GeoNode other = (GeoNodeOuterClass.GeoNode) obj;

      if (hasCode() != other.hasCode()) return false;
      if (hasCode()) {
        if (getCode()
            != other.getCode()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasProvinceCode() != other.hasProvinceCode()) return false;
      if (hasProvinceCode()) {
        if (!getProvinceCode()
            .equals(other.getProvinceCode())) return false;
      }
      if (hasCityCode() != other.hasCityCode()) return false;
      if (hasCityCode()) {
        if (!getCityCode()
            .equals(other.getCityCode())) return false;
      }
      if (hasDistrictCode() != other.hasDistrictCode()) return false;
      if (hasDistrictCode()) {
        if (!getDistrictCode()
            .equals(other.getDistrictCode())) return false;
      }
      if (hasLat() != other.hasLat()) return false;
      if (hasLat()) {
        if (!getLat()
            .equals(other.getLat())) return false;
      }
      if (hasLng() != other.hasLng()) return false;
      if (hasLng()) {
        if (!getLng()
            .equals(other.getLng())) return false;
      }
      if (hasZone() != other.hasZone()) return false;
      if (hasZone()) {
        if (!getZone()
            .equals(other.getZone())) return false;
      }
      if (!getSubNodeList()
          .equals(other.getSubNodeList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasProvinceCode()) {
        hash = (37 * hash) + PROVINCECODE_FIELD_NUMBER;
        hash = (53 * hash) + getProvinceCode().hashCode();
      }
      if (hasCityCode()) {
        hash = (37 * hash) + CITYCODE_FIELD_NUMBER;
        hash = (53 * hash) + getCityCode().hashCode();
      }
      if (hasDistrictCode()) {
        hash = (37 * hash) + DISTRICTCODE_FIELD_NUMBER;
        hash = (53 * hash) + getDistrictCode().hashCode();
      }
      if (hasLat()) {
        hash = (37 * hash) + LAT_FIELD_NUMBER;
        hash = (53 * hash) + getLat().hashCode();
      }
      if (hasLng()) {
        hash = (37 * hash) + LNG_FIELD_NUMBER;
        hash = (53 * hash) + getLng().hashCode();
      }
      if (hasZone()) {
        hash = (37 * hash) + ZONE_FIELD_NUMBER;
        hash = (53 * hash) + getZone().hashCode();
      }
      if (getSubNodeCount() > 0) {
        hash = (37 * hash) + SUBNODE_FIELD_NUMBER;
        hash = (53 * hash) + getSubNodeList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GeoNodeOuterClass.GeoNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static GeoNodeOuterClass.GeoNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static GeoNodeOuterClass.GeoNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static GeoNodeOuterClass.GeoNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GeoNodeOuterClass.GeoNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GeoNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GeoNode)
        GeoNodeOuterClass.GeoNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GeoNodeOuterClass.internal_static_GeoNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GeoNodeOuterClass.internal_static_GeoNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GeoNodeOuterClass.GeoNode.class, GeoNodeOuterClass.GeoNode.Builder.class);
      }

      // Construct using GeoNodeOuterClass.GeoNode.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        name_ = "";
        provinceCode_ = "";
        cityCode_ = "";
        districtCode_ = "";
        lat_ = "";
        lng_ = "";
        zone_ = "";
        if (subNodeBuilder_ == null) {
          subNode_ = java.util.Collections.emptyList();
        } else {
          subNode_ = null;
          subNodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GeoNodeOuterClass.internal_static_GeoNode_descriptor;
      }

      @java.lang.Override
      public GeoNodeOuterClass.GeoNode getDefaultInstanceForType() {
        return GeoNodeOuterClass.GeoNode.getDefaultInstance();
      }

      @java.lang.Override
      public GeoNodeOuterClass.GeoNode build() {
        GeoNodeOuterClass.GeoNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GeoNodeOuterClass.GeoNode buildPartial() {
        GeoNodeOuterClass.GeoNode result = new GeoNodeOuterClass.GeoNode(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(GeoNodeOuterClass.GeoNode result) {
        if (subNodeBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0)) {
            subNode_ = java.util.Collections.unmodifiableList(subNode_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.subNode_ = subNode_;
        } else {
          result.subNode_ = subNodeBuilder_.build();
        }
      }

      private void buildPartial0(GeoNodeOuterClass.GeoNode result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.provinceCode_ = provinceCode_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cityCode_ = cityCode_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.districtCode_ = districtCode_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.lat_ = lat_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.lng_ = lng_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.zone_ = zone_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GeoNodeOuterClass.GeoNode) {
          return mergeFrom((GeoNodeOuterClass.GeoNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GeoNodeOuterClass.GeoNode other) {
        if (other == GeoNodeOuterClass.GeoNode.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasProvinceCode()) {
          provinceCode_ = other.provinceCode_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasCityCode()) {
          cityCode_ = other.cityCode_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasDistrictCode()) {
          districtCode_ = other.districtCode_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasLat()) {
          lat_ = other.lat_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasLng()) {
          lng_ = other.lng_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.hasZone()) {
          zone_ = other.zone_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (subNodeBuilder_ == null) {
          if (!other.subNode_.isEmpty()) {
            if (subNode_.isEmpty()) {
              subNode_ = other.subNode_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureSubNodeIsMutable();
              subNode_.addAll(other.subNode_);
            }
            onChanged();
          }
        } else {
          if (!other.subNode_.isEmpty()) {
            if (subNodeBuilder_.isEmpty()) {
              subNodeBuilder_.dispose();
              subNodeBuilder_ = null;
              subNode_ = other.subNode_;
              bitField0_ = (bitField0_ & ~0x00000100);
              subNodeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSubNodeFieldBuilder() : null;
            } else {
              subNodeBuilder_.addAllMessages(other.subNode_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        for (int i = 0; i < getSubNodeCount(); i++) {
          if (!getSubNode(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readSInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                provinceCode_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                cityCode_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                districtCode_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                lat_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                lng_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                zone_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                GeoNodeOuterClass.GeoNode m =
                    input.readMessage(
                        GeoNodeOuterClass.GeoNode.parser(),
                        extensionRegistry);
                if (subNodeBuilder_ == null) {
                  ensureSubNodeIsMutable();
                  subNode_.add(m);
                } else {
                  subNodeBuilder_.addMessage(m);
                }
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>required sint32 code = 1;</code>
       * @return Whether the code field is set.
       */
      @java.lang.Override
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required sint32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>required sint32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object provinceCode_ = "";
      /**
       * <code>optional string provinceCode = 3;</code>
       * @return Whether the provinceCode field is set.
       */
      public boolean hasProvinceCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string provinceCode = 3;</code>
       * @return The provinceCode.
       */
      public java.lang.String getProvinceCode() {
        java.lang.Object ref = provinceCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            provinceCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string provinceCode = 3;</code>
       * @return The bytes for provinceCode.
       */
      public com.google.protobuf.ByteString
          getProvinceCodeBytes() {
        java.lang.Object ref = provinceCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          provinceCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string provinceCode = 3;</code>
       * @param value The provinceCode to set.
       * @return This builder for chaining.
       */
      public Builder setProvinceCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        provinceCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string provinceCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProvinceCode() {
        provinceCode_ = getDefaultInstance().getProvinceCode();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string provinceCode = 3;</code>
       * @param value The bytes for provinceCode to set.
       * @return This builder for chaining.
       */
      public Builder setProvinceCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        provinceCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object cityCode_ = "";
      /**
       * <code>optional string cityCode = 4;</code>
       * @return Whether the cityCode field is set.
       */
      public boolean hasCityCode() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string cityCode = 4;</code>
       * @return The cityCode.
       */
      public java.lang.String getCityCode() {
        java.lang.Object ref = cityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cityCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cityCode = 4;</code>
       * @return The bytes for cityCode.
       */
      public com.google.protobuf.ByteString
          getCityCodeBytes() {
        java.lang.Object ref = cityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cityCode = 4;</code>
       * @param value The cityCode to set.
       * @return This builder for chaining.
       */
      public Builder setCityCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cityCode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cityCode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCityCode() {
        cityCode_ = getDefaultInstance().getCityCode();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string cityCode = 4;</code>
       * @param value The bytes for cityCode to set.
       * @return This builder for chaining.
       */
      public Builder setCityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        cityCode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object districtCode_ = "";
      /**
       * <code>optional string districtCode = 5;</code>
       * @return Whether the districtCode field is set.
       */
      public boolean hasDistrictCode() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string districtCode = 5;</code>
       * @return The districtCode.
       */
      public java.lang.String getDistrictCode() {
        java.lang.Object ref = districtCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            districtCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string districtCode = 5;</code>
       * @return The bytes for districtCode.
       */
      public com.google.protobuf.ByteString
          getDistrictCodeBytes() {
        java.lang.Object ref = districtCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          districtCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string districtCode = 5;</code>
       * @param value The districtCode to set.
       * @return This builder for chaining.
       */
      public Builder setDistrictCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        districtCode_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string districtCode = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistrictCode() {
        districtCode_ = getDefaultInstance().getDistrictCode();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string districtCode = 5;</code>
       * @param value The bytes for districtCode to set.
       * @return This builder for chaining.
       */
      public Builder setDistrictCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        districtCode_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object lat_ = "";
      /**
       * <code>optional string lat = 6;</code>
       * @return Whether the lat field is set.
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string lat = 6;</code>
       * @return The lat.
       */
      public java.lang.String getLat() {
        java.lang.Object ref = lat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lat_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lat = 6;</code>
       * @return The bytes for lat.
       */
      public com.google.protobuf.ByteString
          getLatBytes() {
        java.lang.Object ref = lat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lat = 6;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lat_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lat = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        lat_ = getDefaultInstance().getLat();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string lat = 6;</code>
       * @param value The bytes for lat to set.
       * @return This builder for chaining.
       */
      public Builder setLatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        lat_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object lng_ = "";
      /**
       * <code>optional string lng = 7;</code>
       * @return Whether the lng field is set.
       */
      public boolean hasLng() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string lng = 7;</code>
       * @return The lng.
       */
      public java.lang.String getLng() {
        java.lang.Object ref = lng_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lng_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lng = 7;</code>
       * @return The bytes for lng.
       */
      public com.google.protobuf.ByteString
          getLngBytes() {
        java.lang.Object ref = lng_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lng_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lng = 7;</code>
       * @param value The lng to set.
       * @return This builder for chaining.
       */
      public Builder setLng(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lng_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lng = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLng() {
        lng_ = getDefaultInstance().getLng();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>optional string lng = 7;</code>
       * @param value The bytes for lng to set.
       * @return This builder for chaining.
       */
      public Builder setLngBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        lng_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object zone_ = "";
      /**
       * <code>optional string zone = 8;</code>
       * @return Whether the zone field is set.
       */
      public boolean hasZone() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string zone = 8;</code>
       * @return The zone.
       */
      public java.lang.String getZone() {
        java.lang.Object ref = zone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string zone = 8;</code>
       * @return The bytes for zone.
       */
      public com.google.protobuf.ByteString
          getZoneBytes() {
        java.lang.Object ref = zone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string zone = 8;</code>
       * @param value The zone to set.
       * @return This builder for chaining.
       */
      public Builder setZone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        zone_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional string zone = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearZone() {
        zone_ = getDefaultInstance().getZone();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>optional string zone = 8;</code>
       * @param value The bytes for zone to set.
       * @return This builder for chaining.
       */
      public Builder setZoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        zone_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.util.List<GeoNodeOuterClass.GeoNode> subNode_ =
        java.util.Collections.emptyList();
      private void ensureSubNodeIsMutable() {
        if (!((bitField0_ & 0x00000100) != 0)) {
          subNode_ = new java.util.ArrayList<GeoNodeOuterClass.GeoNode>(subNode_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          GeoNodeOuterClass.GeoNode, GeoNodeOuterClass.GeoNode.Builder, GeoNodeOuterClass.GeoNodeOrBuilder> subNodeBuilder_;

      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public java.util.List<GeoNodeOuterClass.GeoNode> getSubNodeList() {
        if (subNodeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subNode_);
        } else {
          return subNodeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public int getSubNodeCount() {
        if (subNodeBuilder_ == null) {
          return subNode_.size();
        } else {
          return subNodeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public GeoNodeOuterClass.GeoNode getSubNode(int index) {
        if (subNodeBuilder_ == null) {
          return subNode_.get(index);
        } else {
          return subNodeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder setSubNode(
          int index, GeoNodeOuterClass.GeoNode value) {
        if (subNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubNodeIsMutable();
          subNode_.set(index, value);
          onChanged();
        } else {
          subNodeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder setSubNode(
          int index, GeoNodeOuterClass.GeoNode.Builder builderForValue) {
        if (subNodeBuilder_ == null) {
          ensureSubNodeIsMutable();
          subNode_.set(index, builderForValue.build());
          onChanged();
        } else {
          subNodeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder addSubNode(GeoNodeOuterClass.GeoNode value) {
        if (subNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubNodeIsMutable();
          subNode_.add(value);
          onChanged();
        } else {
          subNodeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder addSubNode(
          int index, GeoNodeOuterClass.GeoNode value) {
        if (subNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubNodeIsMutable();
          subNode_.add(index, value);
          onChanged();
        } else {
          subNodeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder addSubNode(
          GeoNodeOuterClass.GeoNode.Builder builderForValue) {
        if (subNodeBuilder_ == null) {
          ensureSubNodeIsMutable();
          subNode_.add(builderForValue.build());
          onChanged();
        } else {
          subNodeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder addSubNode(
          int index, GeoNodeOuterClass.GeoNode.Builder builderForValue) {
        if (subNodeBuilder_ == null) {
          ensureSubNodeIsMutable();
          subNode_.add(index, builderForValue.build());
          onChanged();
        } else {
          subNodeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder addAllSubNode(
          java.lang.Iterable<? extends GeoNodeOuterClass.GeoNode> values) {
        if (subNodeBuilder_ == null) {
          ensureSubNodeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subNode_);
          onChanged();
        } else {
          subNodeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder clearSubNode() {
        if (subNodeBuilder_ == null) {
          subNode_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          subNodeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public Builder removeSubNode(int index) {
        if (subNodeBuilder_ == null) {
          ensureSubNodeIsMutable();
          subNode_.remove(index);
          onChanged();
        } else {
          subNodeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public GeoNodeOuterClass.GeoNode.Builder getSubNodeBuilder(
          int index) {
        return getSubNodeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public GeoNodeOuterClass.GeoNodeOrBuilder getSubNodeOrBuilder(
          int index) {
        if (subNodeBuilder_ == null) {
          return subNode_.get(index);  } else {
          return subNodeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public java.util.List<? extends GeoNodeOuterClass.GeoNodeOrBuilder> 
           getSubNodeOrBuilderList() {
        if (subNodeBuilder_ != null) {
          return subNodeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subNode_);
        }
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public GeoNodeOuterClass.GeoNode.Builder addSubNodeBuilder() {
        return getSubNodeFieldBuilder().addBuilder(
            GeoNodeOuterClass.GeoNode.getDefaultInstance());
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public GeoNodeOuterClass.GeoNode.Builder addSubNodeBuilder(
          int index) {
        return getSubNodeFieldBuilder().addBuilder(
            index, GeoNodeOuterClass.GeoNode.getDefaultInstance());
      }
      /**
       * <code>repeated .GeoNode subNode = 9;</code>
       */
      public java.util.List<GeoNodeOuterClass.GeoNode.Builder> 
           getSubNodeBuilderList() {
        return getSubNodeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          GeoNodeOuterClass.GeoNode, GeoNodeOuterClass.GeoNode.Builder, GeoNodeOuterClass.GeoNodeOrBuilder> 
          getSubNodeFieldBuilder() {
        if (subNodeBuilder_ == null) {
          subNodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              GeoNodeOuterClass.GeoNode, GeoNodeOuterClass.GeoNode.Builder, GeoNodeOuterClass.GeoNodeOrBuilder>(
                  subNode_,
                  ((bitField0_ & 0x00000100) != 0),
                  getParentForChildren(),
                  isClean());
          subNode_ = null;
        }
        return subNodeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GeoNode)
    }

    // @@protoc_insertion_point(class_scope:GeoNode)
    private static final GeoNodeOuterClass.GeoNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GeoNodeOuterClass.GeoNode();
    }

    public static GeoNodeOuterClass.GeoNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeoNode>
        PARSER = new com.google.protobuf.AbstractParser<GeoNode>() {
      @java.lang.Override
      public GeoNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GeoNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeoNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GeoNodeOuterClass.GeoNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeoNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GeoNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGeoNode.proto\"\246\001\n\007GeoNode\022\014\n\004code\030\001 \002(" +
      "\021\022\014\n\004name\030\002 \002(\t\022\024\n\014provinceCode\030\003 \001(\t\022\020\n" +
      "\010cityCode\030\004 \001(\t\022\024\n\014districtCode\030\005 \001(\t\022\013\n" +
      "\003lat\030\006 \001(\t\022\013\n\003lng\030\007 \001(\t\022\014\n\004zone\030\010 \001(\t\022\031\n" +
      "\007subNode\030\t \003(\0132\010.GeoNode"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GeoNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GeoNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GeoNode_descriptor,
        new java.lang.String[] { "Code", "Name", "ProvinceCode", "CityCode", "DistrictCode", "Lat", "Lng", "Zone", "SubNode", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
